name: Print File Content CI/CD

on: [push, pull_request]

jobs:
  print_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print hello_world.txt content
        run: cat hello_world.txt